version: '3'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: processor
      POSTGRES_USER: ilya
      POSTGRES_PASSWORD: test
    ports:
      - "5433:5432"
    volumes:
      - ./internal/app/database/init/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./internal/app/database/init/fill_dishes.sql:/docker-entrypoint-initdb.d/fill_dishes.sql
