version: '3'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: authorization
      POSTGRES_USER: ilya
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - ./internal/app/database/init/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
